"""Machine-checks the notebook citation format.

A notebook cites a source with a numbered in-text link to an entry of its own
final Markdown cell, headed ``## References``: ``[[1]](#ref-1) (Eq. 41)`` in
prose, and ``1. <a id="ref-1"></a> N. Baddour, ...`` in the References cell.
Equation, figure, and appendix numbers go outside the link, in parentheses,
so a locator such as "Eq. 21" always names the source it belongs to. Nothing
here is generated by executing code, so the format renders the same way in
JupyterLab, GitHub, and the Sphinx docs build.
"""

import json
import re
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_NOTEBOOKS_DIR = _REPO_ROOT / "notebooks"
_CITATION_FILE = _REPO_ROOT / "CITATION.cff"

_REFERENCES_HEADING = "## References"
# In-text citation: the displayed number and the anchor it links to.
_CITATION_PATTERN = re.compile(r"\[\[(\d+)\]\]\(#ref-(\d+)\)")
# Any link to a reference anchor, whatever its displayed text.
_ANCHOR_LINK_PATTERN = re.compile(r"\]\(#ref-(\d+)\)")
# One References entry: its list number, its anchor number, and its text.
_ENTRY_PATTERN = re.compile(r'^(\d+)\. <a id="ref-(\d+)"></a> (.+)$', re.MULTILINE)
# A locator (equation, figure, section, appendix) anywhere in prose...
_LOCATOR_PATTERN = re.compile(r"\b(?:Eqs?|Figs?|Secs?)\.|\bAppendix\b")
# ...and the same locator correctly paired with the citation right before it.
_PAIRED_LOCATOR_PATTERN = re.compile(
    r"\[\[\d+\]\]\(#ref-\d+\)\s+\((?:Eqs?\.|Figs?\.|Secs?\.|Appendix)[^)]*\)"
)
# Author-year labels such as ``[Baddour2019a, Eq. 41]``.
_AUTHOR_YEAR_LABEL_PATTERN = re.compile(r"\[[A-Za-z]+\d{4}[a-z]?[,\]]")
_CODE_GENERATED_BIBLIOGRAPHY = ("bibliography(", "pypft.references")
_ENTRY_DOI_PATTERN = re.compile(r"\[doi:(10\.[^\]]+)\]")
_CITATION_FILE_DOI_PATTERN = re.compile(r"^\s*doi:\s*(10\.\S+)\s*$", re.MULTILINE)


def _notebook_paths() -> list[Path]:
    """List every tracked notebook, in a stable order.

    :returns: The tutorial notebooks' paths, sorted by name.
    :rtype: list[Path]

    """
    return sorted(_NOTEBOOKS_DIR.glob("*.ipynb"))


def _load(path: Path) -> dict:
    """Parse one notebook.

    :param path: The ``.ipynb`` file to read.
    :type path: Path
    :returns: The parsed notebook document.
    :rtype: dict

    """
    return json.loads(path.read_text(encoding="utf-8"))


def _source(cell: dict) -> str:
    """Join one cell's source lines.

    :param cell: A notebook cell.
    :type cell: dict
    :returns: The cell's full source text.
    :rtype: str

    """
    return "".join(cell["source"])


def _is_references_cell(cell: dict) -> bool:
    """Tell whether a cell is a References cell.

    :param cell: A notebook cell.
    :type cell: dict
    :returns: ``True`` for a Markdown cell starting with the References heading.
    :rtype: bool

    """
    return cell["cell_type"] == "markdown" and _source(cell).startswith(
        _REFERENCES_HEADING
    )


def _prose(notebook: dict) -> list[str]:
    """Collect every Markdown cell's source except the References cell's.

    :param notebook: A parsed ``.ipynb`` document.
    :type notebook: dict
    :returns: One source string per prose Markdown cell, in cell order.
    :rtype: list[str]

    """
    return [
        _source(cell)
        for cell in notebook["cells"]
        if cell["cell_type"] == "markdown" and not _is_references_cell(cell)
    ]


def _references_text(notebook: dict) -> str:
    """Return the source of a notebook's References cell.

    :param notebook: A parsed ``.ipynb`` document.
    :type notebook: dict
    :returns: The References cell's source, or ``""`` if there is none.
    :rtype: str

    """
    cells = [_source(cell) for cell in notebook["cells"] if _is_references_cell(cell)]
    assert len(cells) <= 1, "a notebook has at most one References cell"
    return cells[0] if cells else ""


def _cited_numbers(notebook: dict) -> list[int]:
    """List the anchor number of every reference link, in order of appearance.

    :param notebook: A parsed ``.ipynb`` document.
    :type notebook: dict
    :returns: One anchor number per link to ``#ref-<k>``, repeats included.
    :rtype: list[int]

    """
    return [
        int(match.group(1))
        for text in _prose(notebook)
        for match in _ANCHOR_LINK_PATTERN.finditer(text)
    ]


def _entries(notebook: dict) -> list[re.Match[str]]:
    """List the entries of a notebook's References cell, in order.

    :param notebook: A parsed ``.ipynb`` document.
    :type notebook: dict
    :returns: One ``_ENTRY_PATTERN`` match per entry.
    :rtype: list[re.Match[str]]

    """
    return list(_ENTRY_PATTERN.finditer(_references_text(notebook)))


@pytest.mark.parametrize("path", _notebook_paths(), ids=lambda p: p.name)
def test_every_citation_link_has_a_references_entry(path):
    """Every ``](#ref-k)`` link resolves to an anchor in the References cell."""
    notebook = _load(path)
    anchors = {int(entry.group(2)) for entry in _entries(notebook)}
    dangling = set(_cited_numbers(notebook)) - anchors
    assert not dangling, f"{path.name} links to missing reference(s): {dangling}"


@pytest.mark.parametrize("path", _notebook_paths(), ids=lambda p: p.name)
def test_every_references_entry_is_cited(path):
    """No References entry is left uncited in the notebook's prose."""
    notebook = _load(path)
    anchors = {int(entry.group(2)) for entry in _entries(notebook)}
    uncited = anchors - set(_cited_numbers(notebook))
    assert not uncited, f"{path.name} lists uncited reference(s): {uncited}"


@pytest.mark.parametrize("path", _notebook_paths(), ids=lambda p: p.name)
def test_references_are_numbered_in_first_citation_order(path):
    """Entries are numbered ``1..K`` exactly in order of first citation."""
    notebook = _load(path)
    entries = _entries(notebook)
    for entry in entries:
        assert entry.group(1) == entry.group(
            2
        ), f"{path.name}: entry {entry.group(1)} carries anchor ref-{entry.group(2)}"
    expected = list(range(1, len(entries) + 1))
    assert [int(entry.group(1)) for entry in entries] == expected

    first_citations = list(dict.fromkeys(_cited_numbers(notebook)))
    assert first_citations == expected, (
        f"{path.name}: references first cited in order {first_citations}, "
        f"but numbered {expected}"
    )
    for text in _prose(notebook):
        for match in _CITATION_PATTERN.finditer(text):
            assert match.group(1) == match.group(2), (
                f"{path.name}: citation [{match.group(1)}] links to "
                f"#ref-{match.group(2)}"
            )


@pytest.mark.parametrize("path", _notebook_paths(), ids=lambda p: p.name)
def test_references_cell_is_the_final_cell_of_a_citing_notebook(path):
    """A citing notebook ends with its References cell; others have none."""
    notebook = _load(path)
    if not _cited_numbers(notebook):
        assert not _references_text(
            notebook
        ), f"{path.name} has a References cell but cites nothing"
        return
    assert _is_references_cell(notebook["cells"][-1]), (
        f"{path.name} cites references but does not end with a "
        f"{_REFERENCES_HEADING!r} cell"
    )


@pytest.mark.parametrize("path", _notebook_paths(), ids=lambda p: p.name)
def test_every_locator_is_paired_with_a_citation(path):
    """An equation, figure, or appendix number always follows its citation."""
    notebook = _load(path)
    for text in _prose(notebook):
        unpaired = _LOCATOR_PATTERN.findall(_PAIRED_LOCATOR_PATTERN.sub("", text))
        assert not unpaired, (
            f"{path.name}: locator(s) {unpaired} not written as "
            f"'[[k]](#ref-k) (Eq. N)' in:\n{text}"
        )


@pytest.mark.parametrize("path", _notebook_paths(), ids=lambda p: p.name)
def test_no_author_year_labels_or_generated_bibliography_remain(path):
    """No ``[Key2019a]`` labels or code-generated bibliography cells remain."""
    notebook = _load(path)
    for cell in notebook["cells"]:
        text = _source(cell)
        if cell["cell_type"] == "markdown":
            labels = _AUTHOR_YEAR_LABEL_PATTERN.findall(text)
            assert not labels, f"{path.name} uses author-year label(s): {labels}"
        for marker in _CODE_GENERATED_BIBLIOGRAPHY:
            assert marker not in text, f"{path.name} still contains {marker!r}"


@pytest.mark.parametrize("path", _notebook_paths(), ids=lambda p: p.name)
def test_every_references_entry_doi_is_listed_in_the_citation_file(path):
    """Each entry carries a DOI that ``CITATION.cff``'s references also list."""
    listed = set(
        _CITATION_FILE_DOI_PATTERN.findall(_CITATION_FILE.read_text(encoding="utf-8"))
    )
    for entry in _entries(_load(path)):
        dois = _ENTRY_DOI_PATTERN.findall(entry.group(3))
        assert len(dois) == 1, f"{path.name}: entry {entry.group(1)} has no DOI link"
        assert (
            dois[0] in listed
        ), f"{path.name}: DOI {dois[0]} is not listed in {_CITATION_FILE.name}"
